---
- name: "Purge systemd service {{ service_name }}"
  shell:
    cmd: "{{ item }}"
  with_items:
    - "systemctl stop {{ service_name }}"
    - "systemctl disable {{ service_name }}"
    - "rm {{ eap_systemd_service_path }}"
    - "systemctl daemon-reload"
