version: "3.9"

services:
  host:
    image: journey-log/ansible-control-node
    build:
      context: ../common/images/control-node
    volumes:
      - ../common/init:/srv/init
      - .:/srv/data
    working_dir: /srv/data

  db:
    #    image: quay.io/ansible/ansible-runner
    image: journey-log/ansible-managed-node
    build:
      context: ../common/images/managed-node
    volumes:
      - ../common/init:/srv/init
