version: "3.9"

services:
  host:
    image: journey-log/ansible-control-node
    build:
      context: ../common/images/control-node
    volumes:
      - ../common/init:/srv/init
      - .:/srv/data
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /srv/data

  as:
    image: journey-log/ansible-wildfly
    build:
      context: context
