---
# --- JBoss EAP Artifact
# ---
eap_version: "{{ version }}"

# --- JBoss EAP Installation
# ---
eap_user: "jboss"
eap_install_workdir: "/opt/{{ eap_user }}"
eap_home: "{{ eap_install_workdir }}/{{ service_name }}-{{ (eap_version.split('.'))[0:2] | join('.') }}"

# TODO: implement custom mode from standalone or domain
# ---   eap_home/(eap_mode=standalone|domain) > eap_home/custom_mode_name
eap_mode: "standalone"

# TODO: implement config base check for trigger setup role update
eap_config_base: "{{ eap_mode }}.xml"

# --- JBoss EAP Setup
# ---
eap_systemd_service_path: "/usr/lib/systemd/system/{{ service_name }}.service"
eap_tmp_dir_path: "{{ eap_home }}/tmp"
eap_cli_dir_path: "{{ eap_tmp_dir_path }}/cli"

eap_admin_username: "admin"
eap_admin_password: "admin"

# --- JBoss EAP Runtime
# ---
eap_java_package_name: "java-{{ java_version }}-openjdk-headless"

# TODO: implement binding address check for trigger setup role update
eap_bind_addr: "127.0.0.1"
eap_bind_addr_management: "0.0.0.0"
