---
- name: "Check arguments"
  assert:
    quiet: yes
    that:
      - apply_cli is defined

- name: "Retrieve local CLI file state"
  delegate_to: localhost
  stat:
    path: "{{ apply_cli }}"
  register: eap_cli_local_file
