---
- name: "Check arguments"
  assert:
    quiet: yes
    that:
      - eap_cli_local_file is defined
      - eap_cli_local_file.stat is defined

- name: "Upload local files to remote"
  copy:
    src: "{{ eap_cli_local_file.stat.path }}"#/{{ eap_mode }}/"
    dest: "{{ eap_cli_dir_path }}/"

- name: "Retrieve remote files state"
  stat:
    path: "{{ eap_cli_dir_path }}"
  register: eap_cli_remote_file
